language: php

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - composer install --dev --no-interaction

script:
  - composer run phpunit-coverage-text
  - composer run phpcs

notifications:
    email: false
