<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class CurrencyModelItem
{
    /**
     * @var CurrencyModel
     */
    protected $data;

    /**
     * @return CurrencyModel
     */
    public function getData(): ?CurrencyModel
    {
        return $this->data;
    }

    /**
     * @param CurrencyModel $data
     *
     * @return self
     */
    public function setData(?CurrencyModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
