<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class CustomerModelCollectionMeta
{
    /**
     * @var PaginationModel
     */
    protected $pagination;

    /**
     * @return PaginationModel
     */
    public function getPagination(): ?PaginationModel
    {
        return $this->pagination;
    }

    /**
     * @param PaginationModel $pagination
     *
     * @return self
     */
    public function setPagination(?PaginationModel $pagination): self
    {
        $this->pagination = $pagination;

        return $this;
    }
}
