<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class CustomerAddedTagModelItem
{
    /**
     * @var CustomerAddedTagModel
     */
    protected $data;

    /**
     * @return CustomerAddedTagModel
     */
    public function getData(): ?CustomerAddedTagModel
    {
        return $this->data;
    }

    /**
     * @param CustomerAddedTagModel $data
     *
     * @return self
     */
    public function setData(?CustomerAddedTagModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
