<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class CustomerTagModelItem
{
    /**
     * @var CustomerTagModel
     */
    protected $data;

    /**
     * @return CustomerTagModel
     */
    public function getData(): ?CustomerTagModel
    {
        return $this->data;
    }

    /**
     * @param CustomerTagModel $data
     *
     * @return self
     */
    public function setData(?CustomerTagModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
