<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class CustomerUpdateModelAddresses
{
    /**
     * @var AddressModel
     */
    protected $invoice;
    /**
     * @var AddressModel
     */
    protected $delivery;

    /**
     * @return AddressModel
     */
    public function getInvoice(): ?AddressModel
    {
        return $this->invoice;
    }

    /**
     * @param AddressModel $invoice
     *
     * @return self
     */
    public function setInvoice(?AddressModel $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }

    /**
     * @return AddressModel
     */
    public function getDelivery(): ?AddressModel
    {
        return $this->delivery;
    }

    /**
     * @param AddressModel $delivery
     *
     * @return self
     */
    public function setDelivery(?AddressModel $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }
}
