<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class CustomerExternalServicesModelItem
{
    /**
     * @var CustomerExternalServicesModel
     */
    protected $data;

    /**
     * @return CustomerExternalServicesModel
     */
    public function getData(): ?CustomerExternalServicesModel
    {
        return $this->data;
    }

    /**
     * @param CustomerExternalServicesModel $data
     *
     * @return self
     */
    public function setData(?CustomerExternalServicesModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
