<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class MediaFileModelItem
{
    /**
     * @var MediaFileModel
     */
    protected $data;

    /**
     * @return MediaFileModel
     */
    public function getData(): ?MediaFileModel
    {
        return $this->data;
    }

    /**
     * @param MediaFileModel $data
     *
     * @return self
     */
    public function setData(?MediaFileModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
