<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class OrderAddressCollection
{
    /**
     * @var OrderAddressModel
     */
    protected $data;

    /**
     * @return OrderAddressModel
     */
    public function getData(): ?OrderAddressModel
    {
        return $this->data;
    }

    /**
     * @param OrderAddressModel $data
     *
     * @return self
     */
    public function setData(?OrderAddressModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
