<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class OrderExternalServiceModelCollection
{
    /**
     * A list of order external services.
     *
     * @var OrderExternalServiceModel[]
     */
    protected $data;

    /**
     * A list of order external services.
     *
     * @return OrderExternalServiceModel[]
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * A list of order external services.
     *
     * @param OrderExternalServiceModel[] $data
     *
     * @return self
     */
    public function setData(?array $data): self
    {
        $this->data = $data;

        return $this;
    }
}
