<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class OrderCommentModelItem
{
    /**
     * @var OrderCommentModel
     */
    protected $data;

    /**
     * @return OrderCommentModel
     */
    public function getData(): ?OrderCommentModel
    {
        return $this->data;
    }

    /**
     * @param OrderCommentModel $data
     *
     * @return self
     */
    public function setData(?OrderCommentModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
