<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class OrderItemModelItem
{
    /**
     * @var OrderItemModel
     */
    protected $data;

    /**
     * @return OrderItemModel
     */
    public function getData(): ?OrderItemModel
    {
        return $this->data;
    }

    /**
     * @param OrderItemModel $data
     *
     * @return self
     */
    public function setData(?OrderItemModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
