<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class OrderExternalServicesModelItem
{
    /**
     * @var OrderExternalServiceModel
     */
    protected $data;

    /**
     * @return OrderExternalServiceModel
     */
    public function getData(): ?OrderExternalServiceModel
    {
        return $this->data;
    }

    /**
     * @param OrderExternalServiceModel $data
     *
     * @return self
     */
    public function setData(?OrderExternalServiceModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
