<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class OrderModelItem
{
    /**
     * @var OrderModel
     */
    protected $data;

    /**
     * @return OrderModel
     */
    public function getData(): ?OrderModel
    {
        return $this->data;
    }

    /**
     * @param OrderModel $data
     *
     * @return self
     */
    public function setData(?OrderModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
