<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class PaymentMethodModelItem
{
    /**
     * @var PaymentMethodModel
     */
    protected $data;

    /**
     * @return PaymentMethodModel
     */
    public function getData(): ?PaymentMethodModel
    {
        return $this->data;
    }

    /**
     * @param PaymentMethodModel $data
     *
     * @return self
     */
    public function setData(?PaymentMethodModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
