<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class PricelistModelItem
{
    /**
     * @var PricelistModel
     */
    protected $data;

    /**
     * @return PricelistModel
     */
    public function getData(): ?PricelistModel
    {
        return $this->data;
    }

    /**
     * @param PricelistModel $data
     *
     * @return self
     */
    public function setData(?PricelistModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
