<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductMetaDataModelItem
{
    /**
     * @var ProductMetaDataModel
     */
    protected $data;

    /**
     * @return ProductMetaDataModel
     */
    public function getData(): ?ProductMetaDataModel
    {
        return $this->data;
    }

    /**
     * @param ProductMetaDataModel $data
     *
     * @return self
     */
    public function setData(?ProductMetaDataModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
