<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductUnitModelItem
{
    /**
     * @var ProductUnitModel
     */
    protected $data;

    /**
     * @return ProductUnitModel
     */
    public function getData(): ?ProductUnitModel
    {
        return $this->data;
    }

    /**
     * @param ProductUnitModel $data
     *
     * @return self
     */
    public function setData(?ProductUnitModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
