<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductVariantPriceModelItem
{
    /**
     * @var ProductVariantPriceModel
     */
    protected $data;

    /**
     * @return ProductVariantPriceModel
     */
    public function getData(): ?ProductVariantPriceModel
    {
        return $this->data;
    }

    /**
     * @param ProductVariantPriceModel $data
     *
     * @return self
     */
    public function setData(?ProductVariantPriceModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
