<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductVariantModelItem
{
    /**
     * @var ProductVariantModel
     */
    protected $data;

    /**
     * @return ProductVariantModel
     */
    public function getData(): ?ProductVariantModel
    {
        return $this->data;
    }

    /**
     * @param ProductVariantModel $data
     *
     * @return self
     */
    public function setData(?ProductVariantModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
