<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductMediaFileLinkModelItem
{
    /**
     * @var ProductMediaFileLinkModel
     */
    protected $data;

    /**
     * @return ProductMediaFileLinkModel
     */
    public function getData(): ?ProductMediaFileLinkModel
    {
        return $this->data;
    }

    /**
     * @param ProductMediaFileLinkModel $data
     *
     * @return self
     */
    public function setData(?ProductMediaFileLinkModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
