<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductMetaDataTypeModelItem
{
    /**
     * @var ProductMetaDataTypeModel
     */
    protected $data;

    /**
     * @return ProductMetaDataTypeModel
     */
    public function getData(): ?ProductMetaDataTypeModel
    {
        return $this->data;
    }

    /**
     * @param ProductMetaDataTypeModel $data
     *
     * @return self
     */
    public function setData(?ProductMetaDataTypeModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
