<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductManufacturerModelItem
{
    /**
     * @var ProductManufacturerModel
     */
    protected $data;

    /**
     * @return ProductManufacturerModel
     */
    public function getData(): ?ProductManufacturerModel
    {
        return $this->data;
    }

    /**
     * @param ProductManufacturerModel $data
     *
     * @return self
     */
    public function setData(?ProductManufacturerModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
