<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductVariantAttributeModelItem
{
    /**
     * @var ProductVariantAttributeModel
     */
    protected $data;

    /**
     * @return ProductVariantAttributeModel
     */
    public function getData(): ?ProductVariantAttributeModel
    {
        return $this->data;
    }

    /**
     * @param ProductVariantAttributeModel $data
     *
     * @return self
     */
    public function setData(?ProductVariantAttributeModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
