<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductStockStatusModelItem
{
    /**
     * @var ProductStockStatusModel
     */
    protected $data;

    /**
     * @return ProductStockStatusModel
     */
    public function getData(): ?ProductStockStatusModel
    {
        return $this->data;
    }

    /**
     * @param ProductStockStatusModel $data
     *
     * @return self
     */
    public function setData(?ProductStockStatusModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
