<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductCategoryLinkModelItem
{
    /**
     * @var ProductCategoryLinkModel
     */
    protected $data;

    /**
     * @return ProductCategoryLinkModel
     */
    public function getData(): ?ProductCategoryLinkModel
    {
        return $this->data;
    }

    /**
     * @param ProductCategoryLinkModel $data
     *
     * @return self
     */
    public function setData(?ProductCategoryLinkModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
