<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductCategoryModelItem
{
    /**
     * @var ProductCategoryModel
     */
    protected $data;

    /**
     * @return ProductCategoryModel
     */
    public function getData(): ?ProductCategoryModel
    {
        return $this->data;
    }

    /**
     * @param ProductCategoryModel $data
     *
     * @return self
     */
    public function setData(?ProductCategoryModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
