<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductMetaLanguageDataModelItem
{
    /**
     * @var ProductMetaLanguageDataModel
     */
    protected $data;

    /**
     * @return ProductMetaLanguageDataModel
     */
    public function getData(): ?ProductMetaLanguageDataModel
    {
        return $this->data;
    }

    /**
     * @param ProductMetaLanguageDataModel $data
     *
     * @return self
     */
    public function setData(?ProductMetaLanguageDataModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
