<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductVatRateModelItem
{
    /**
     * @var ProductVatRateModel
     */
    protected $data;

    /**
     * @return ProductVatRateModel
     */
    public function getData(): ?ProductVatRateModel
    {
        return $this->data;
    }

    /**
     * @param ProductVatRateModel $data
     *
     * @return self
     */
    public function setData(?ProductVatRateModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
