<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ProductModelItem
{
    /**
     * @var ProductModel
     */
    protected $data;

    /**
     * @return ProductModel
     */
    public function getData(): ?ProductModel
    {
        return $this->data;
    }

    /**
     * @param ProductModel $data
     *
     * @return self
     */
    public function setData(?ProductModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
