<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Model;

class ShippingMethodModelItem
{
    /**
     * @var ShippingMethodModel
     */
    protected $data;

    /**
     * @return ShippingMethodModel
     */
    public function getData(): ?ShippingMethodModel
    {
        return $this->data;
    }

    /**
     * @param ShippingMethodModel $data
     *
     * @return self
     */
    public function setData(?ShippingMethodModel $data): self
    {
        $this->data = $data;

        return $this;
    }
}
