<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Starweb\Api\Client\Exception;

class PutProductsVatRateNotFoundException extends \RuntimeException implements ClientException
{
    private $errorModel;

    public function __construct(\Starweb\Api\Client\Model\ErrorModel $errorModel)
    {
        parent::__construct('Entity not found', 404);
        $this->errorModel = $errorModel;
    }

    public function getErrorModel()
    {
        return $this->errorModel;
    }
}
